apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: developers
spec:
  type: team
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: dev-members
  description: A group of developers
spec:
  targets:
    - ./tp.babparn.yaml