apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: tp.babparn
spec:
  profile:
    displayName: Mart TP Coder
    email: tp.babparn@gmail.com
    picture: https://avatars.githubusercontent.com/u/34801905?v=4
  memberOf: [developers]